package com.example.chatapi.model;

public enum MessageType {
    CHAT,
    UNSEEN,
    FRIEND_ONLINE,
    FRIEND_OFFLINE,
    MESSAGE_DELIVERY_UPDATE,
    FRIEND_REQUEST,

    FRIEND_REQUEST_ACCEPTED,
    FRIEND_REQUEST_DECLINED,
    FRIEND_REQUEST_CANCELED
}
